# 机场订阅，名称不能重复
proxy-providers:
  Airport_01:
    type: http
    interval: 1800
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: DIRECT
    url: ""
      
# 用于下载订阅时指定UA
global-ua: clash
    
# 全局配置
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
ipv6: false
allow-lan: true
unified-delay: true
tcp-concurrent: true
  
geodata-mode: false
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 48
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"
  
# 控制面板
external-controller: 127.0.0.1:9090
secret: ""
external-ui: ui
external-ui-url: "https://ghp.ci/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

# 匹配进程 always/strict/off
find-process-mode: strict
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 30

# 策略组选择和fakeip缓存
profile:
  store-selected: true
  store-fake-ip: true
  
# 流量嗅探
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com
  skip-domain:
    - "Mijia Cloud"
    - "dlg.io.mi.com"
    - "+.push.apple.com"
    - "+.apple.com"
    
# 代理模式
tun:
  enable: true
  stack: mixed
  mtu: 9000
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  
# DNS模块
dns:
  # 启用DNS服务器
  enable: true
  # DNS服务器监听地址和端口
  listen: 0.0.0.0:1053
  # 禁用IPv6解析
  ipv6: false
  # 遵循规则匹配
  respect-rules: true

  # DNS解析模式：fake-ip
  # fake-ip模式会为域名分配一个虚拟IP，可以减少DNS查询次数，提高性能
  enhanced-mode: fake-ip
  # fake-ip的IP地址范围
  fake-ip-range: 28.0.0.1/8

  # fake-ip过滤模式：黑名单
  # blacklist: 匹配的域名不使用fake-ip
  # whitelist: 只有匹配的域名才使用fake-ip
  fake-ip-filter-mode: blacklist
  
  # 不使用fake-ip的域名列表
  fake-ip-filter:
    - "+.lan"          # 本地局域网域名
    - "+.local"        # 本地域名
    - geosite:private  # 私有域名
    - geosite:cn       # 中国域名

  # 默认DNS服务器（阿里DNS和腾讯DNS）
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29

  # 代理服务器使用的DNS服务器
  proxy-server-nameserver:
    - 223.5.5.5
    - 119.29.29.29

  # 普通DNS查询使用的服务器
  nameserver:
    - 223.5.5.5
    - 119.29.29.29

  # DNS策略：根据不同域名使用不同的DNS服务器
  nameserver-policy:
    # 国内域名使用国内DNS
    "rule-set:private_domain,cn_domain":
      - 223.5.5.5
      - 119.29.29.29
    # 国外域名使用国外DNS（Cloudflare和Google的DNS over HTTPS）
    "rule-set:geolocation-!cn":
      - "https://dns.cloudflare.com/dns-query"
      - "https://dns.google/dns-query"
   
proxies:
- name: "直连"
  type: direct
  udp: true
 
# 锚点
pr: &pr {type: select, proxies: [🚀 节点选择,⭐ 故转,🌐 均衡,🇺🇲 美国均衡,🇸🇬 加坡故转,🇯🇵 日本故转,🇺🇲 美国故转,🇯🇵 日本自动,🇸🇬 加坡自动,🇭🇰 香港自动,🇺🇲 美国自动,♻️ 自动选择,DIRECT]}
us: &us {type: select, proxies: [🇺🇲 美国故转,🇺🇲 美国均衡,🇺🇲 美国自动,♻️ 自动选择, DIRECT]}
# 策略组
proxy-groups:
  - {name: 🚀 节点选择, type: select, proxies: [⭐ 故转,🌐 均衡,🇺🇲 美国均衡,🇸🇬 加坡故转,🇯🇵 日本故转,🇺🇲 美国故转,🇯🇵 日本自动,🇸🇬 加坡自动,🇭🇰 香港自动,🇺🇲 美国自动,♻️ 自动选择,DIRECT]}
  - {name: 📹 YouTube,!!merge <<: *pr}
  - {name: 🍀 Google,!!merge <<: *pr}
  - {name: 🤖 ChatGPT,!!merge <<: *us}
  - {name: 🐬 外贸,!!merge <<: *pr}
  - {name: 🎵 TikTok,!!merge <<: *pr}
  - {name: 📲 Telegram,!!merge <<: *pr}
  - {name: 🎥 NETFLIX,!!merge <<: *pr}
  - {name: ✈️ Speedtest,!!merge <<: *pr}
  - {name: 💶 PayPal,!!merge <<: *pr}
  - {name: ☁️ cloudflare,!!merge <<: *pr}
  - {name: 🍎 Apple, type: select, proxies: [DIRECT, 🚀 节点选择]}
  - {name: 🎯 全球直连, type: select, proxies: [DIRECT, 🚀 节点选择]}
  - {name: 🐟 漏网之鱼, type: select, proxies: [DIRECT, 🚀 节点选择]}

  # 节点筛选
  - {name: 🇸🇬 加坡故转, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(新加坡|坡|狮城|SG|sg|SIN|Singapore))^((?!(家宽|游戏|剩余|国内|海外|官网)).)*$"}
  - {name: 🇯🇵 日本故转, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(日|东京|大阪|埼玉|JP|NRT|KIX|FUK|(?i)Japan))^((?!(家宽|游戏|剩余|国内|海外|官网)).)*$"}
  - {name: 🇺🇲 美国故转, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(美|us|US|(?i)States|America))^((?!(家宽|游戏|剩余|国内|海外|官网)).)*$"}
  - {name: ⭐ 故转, type: fallback, include-all: true, tolerance: 20, interval: 300, filter: "^((?!(家宽|游戏|剩余|国内|海外|官网)).)*$" }
  
  - {name: 🌐 均衡, type: load-balance, include-all: true, tolerance: 20, interval: 300, filter: "^((?!(家宽|游戏|剩余|国内|海外|官网)).)*$" }
  - {name: 🇺🇲 美国均衡, type: load-balance, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(美|us|US|(?i)States|America))^((?!(家宽|游戏|剩余|国内|海外|官网)).)*$"}

  - {name: 🇯🇵 日本自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(日|东京|大阪|埼玉|JP|NRT|KIX|FUK|(?i)Japan))^((?!(家宽|游戏|剩余|国内|海外|官网)).)*$"}
  - {name: 🇸🇬 加坡自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(新加坡|坡|狮城|SG|sg|SIN|Singapore))^((?!(家宽|游戏|剩余|国内|海外|官网)).)*$"}
  - {name: 🇭🇰 香港自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(香港|HK|Hong Kong|🇭🇰|HongKong|HKG))^((?!(家宽|游戏|剩余|国内|海外|官网)).)*$"}
  - {name: 🇺🇲 美国自动, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?=.*(美|us|US|(?i)States|America))^((?!(家宽|游戏|剩余|国内|海外|官网)).)*$"}
  
  - {name: ♻️ 自动选择, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "^((?!(直连|家宽|游戏|剩余|国内|海外|官网)).)*$"}
  
rules:
  - RULE-SET,private_domain,DIRECT
  - RULE-SET,my_direct,DIRECT
  - RULE-SET,apple_domain,🍎 Apple
  - RULE-SET,my_proxylite,🚀 节点选择
  - RULE-SET,my_ai,🤖 ChatGPT
  - RULE-SET,openai_domain,🤖 ChatGPT
  - RULE-SET,github_domain,🚀 节点选择
  - RULE-SET,youtube_domain,📹 YouTube
  - RULE-SET,facebook_domain,🐬 外贸
  - RULE-SET,whatsapp_domain,🐬 外贸
  - RULE-SET,instagram_domain,🐬 外贸 
  - RULE-SET,linkedin_domain,🐬 外贸
  - RULE-SET,x_domain,🐬 外贸
  - RULE-SET,google_domain,🍀 Google 
  - RULE-SET,onedrive_domain,🚀 节点选择
  - RULE-SET,microsoft_domain,🚀 节点选择
  - RULE-SET,cloudflare_domain,☁️ cloudflare
  - RULE-SET,tiktok_domain,🎵 TikTok
  - RULE-SET,speedtest_domain,✈️ Speedtest
  - RULE-SET,telegram_domain,📲 Telegram
  - RULE-SET,netflix_domain,🎥 NETFLIX
  - RULE-SET,paypal_domain,💶 PayPal
  - RULE-SET,geolocation-!cn,🚀 节点选择
  - RULE-SET,cn_domain,🎯 全球直连
  - RULE-SET,google_ip,🍀 Google,no-resolve
  - RULE-SET,facebook_ip,🐬 外贸,no-resolve
  - RULE-SET,netflix_ip,🎥 NETFLIX,no-resolve
  - RULE-SET,telegram_ip,📲 Telegram,no-resolve
  - RULE-SET,cloudflare_ip,☁️ cloudflare,no-resolve
  - RULE-SET,cn_ip,🎯 全球直连
  - MATCH,🐟 漏网之鱼
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
rule-providers: 
  private_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  my_proxylite: {!!merge <<: *class, url: "https://raw.githubusercontent.com/hiven425/hiven/refs/heads/master/config/ProxyLite.list"}
  my_ai: {!!merge <<: *class, url: "https://raw.githubusercontent.com/hiven425/hiven/refs/heads/master/config/AI.list"}
  my_direct: {!!merge <<: *class, url: "https://raw.githubusercontent.com/hiven425/hiven/refs/heads/master/config/Direct.list"}
  youtube_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
  openai_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/openai.mrs"}
  google_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
  github_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
  telegram_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
  netflix_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}
  paypal_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
  onedrive_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs"}
  microsoft_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  apple_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs"}
  speedtest_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs"}
  tiktok_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"}
  gfw_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs"}
  geolocation-!cn: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
  facebook_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/facebook.mrs"}
  whatsapp_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/whatsapp.mrs"}
  instagram_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/instagram.mrs"}
  linkedin_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/linkedin.mrs"}
  x_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/x.mrs"}
  cloudflare_domain: {!!merge <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cloudflare.mrs"}


  cn_ip: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  google_ip: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
  telegram_ip: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
  netflix_ip: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}
  facebook_ip: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/facebook.mrs"}
  cloudflare_ip: {!!merge <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cloudflare.mrs"}
