payload:
  - DOMAIN-SUFFIX,dns.google
  - DOMAIN-SUFFIX,1dot1dot1dot1.cloudflare-dns.com
  - DOMAIN-SUFFIX,dot.sb
  - DOMAIN-SUFFIX,dns.umbrella.com
  - DOMAIN-SUFFIX,dns.quad9.net
  - DOMAIN-SUFFIX,cloudflare-dns.com
  - DOMAIN-SUFFIX,doh.dns.sb
  - DOMAIN-SUFFIX,doh.opendns.com
  - DOMAIN-SUFFIX,hk-hkg.doh.sb
  - DOMAIN-SUFFIX,keeflys.com
  - DOMAIN-SUFFIX,cloudflare.com
  - DOMAIN-SUFFIX,tktn.be
  - DOMAIN-SUFFIX,guagua.info
  - DOMAIN-SUFFIX,gcore.com
  - DOMAIN-SUFFIX,huaweicloud.com
  - DOMAIN-SUFFIX,qichiyu.com
  - DOMAIN-SUFFIX,gmail.com
  - DOMAIN-SUFFIX,outlook.com
  - DOMAIN-SUFFIX,office365.com
  - DOMAIN-SUFFIX,alibaba.com
  - DOMAIN-SUFFIX,made-in-china.com
  - DOMAIN-SUFFIX,globalsources.com
  - DOMAIN-SUFFIX,ec21.com
  - DOMAIN-SUFFIX,v2rayssr.com
  - DOMAIN-SUFFIX,duyaoss.com
  - DOMAIN-SUFFIX,missav.ai
  - DOMAIN-SUFFIX,pages.dev
  - DOMAIN-SUFFIX,huggingface.co
  - DOMAIN-SUFFIX,hf.space
  - DOMAIN-SUFFIX,faviconkit.com
  - DOMAIN-SUFFIX,posthog.com
  - DOMAIN-SUFFIX,smithery.ai
  - DOMAIN-SUFFIX,npmjs.org
  - DOMAIN-SUFFIX,synology.com
